### PR TITLE
Fixed Docs

### PR DESCRIPTION
**Pull request by Dhruvacube**
## Summary
Now the docs are building without any warning

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Dhruvacube** [comment]
Yess now the docs are building

**Comment by Dhruvacube** [comment]
Hey @StockerMC now you can review it!

**Comment by StockerMC** [comment]
Thanks for the PR. I fixed the warnings when building docs in the [latest commits](https://github.com/StockerMC/discord.py/compare/9862c69f4e47...e1a18e458cf5).

**Comment by Dhruvacube** [comment]
Ohh good then

**Pull request closed without merging**
